<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <!-- Root Element -->
    <xs:element name="options" type="optionsType"/>

    <!-- Main Options Type -->
    <xs:complexType name="optionsType">
        <xs:sequence>
            <xs:element name="list" type="optionsListType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Options List Type -->
    <xs:complexType name="optionsListType">
        <xs:sequence>
            <xs:element name="item" type="optionsItemType" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- Options Item Type -->
    <xs:complexType name="optionsItemType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="title" type="xs:string" use="required"/>
                <xs:attribute name="value" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

</xs:schema>
