"""check.py — is a generated application sound? (ADR 0027 §7.10)

Run by `generate.py --check`. It decides; the skill only relays. In order, and any failure exits 1:

  1  secrets     every value of a key that names a secret is one `${VAR}`; no literal secret shape anywhere;
                 every `${VAR}` used is declared in docker/.env.example and docs/configuration.md; and every
                 placeholder in an appsettings file is set by the compose service that runs it
  2  structure   the files no validator reads — the application maps, the profile trees and their node files —
                 are well-formed, with the root and the required attributes and children the knowledge base's
                 `workspace-minimum` table records
  3  routes      every route of sitemap.json names a page that exists (exact case), the landing route is first
                 and is not `/`, `/login` exists with a page holding a login component
  4  validators  validate_config, resolve_components and validate_model over the generated workspaces — and
                 validate_process when the design has a process. Never over the copied base, and never `--all`
                 over the root: a copied base's own findings are not the generator's

INFO is allowed, and so is `NO_SCHEMA` on a sitemap.json, which every site map gets. Everything else a generated
file causes is SCAFFOLD_VALIDATION_FAILED with the validator's own line quoted. A validator that cannot run is
its own code, and exits 3. Imported by generate.py; stdlib only.
"""

import json
import os
import re
import subprocess
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

SCRIPTS = Path(__file__).resolve().parents[3] / "scripts"
SECRET_KEY = re.compile(r"password|secret|key|token|connectionstring", re.IGNORECASE)
PLACEHOLDER = re.compile(r"\$\{([A-Za-z_][A-Za-z0-9_]*)")
WHOLE_PLACEHOLDER = re.compile(r"\$\{[A-Za-z_][A-Za-z0-9_]*\}\Z")
YAML_PAIR = re.compile(r'^(\s*)"?([A-Za-z0-9_.\-]+)"?:\s*(.*?)\s*$')
FINDING = re.compile(r"^(ERROR|WARN|INFO) ([A-Z_]+) (.*)$")
LITERAL_SECRET = re.compile(
    r"(?i)\b(password|pwd|secret|apikey|api_key|access_token|client_secret)\b\s*[=:]\s*['\"]?(?!\$\{|<|\s|['\"]?$)[^\s'\",;]{3,}")
PRIVATE_KEY = re.compile(r"-----BEGIN [A-Z ]*PRIVATE KEY-----")
SHELL_ONLY = {"PATH"}  # a variable of the image's shell, not a deployment variable
KNOWN_RULES = {"landing-first", "login-route", "page-per-route", "login-component", "profile-tab",
               "members-group", "node-per-folder"}
ALLOWED_ON_SITEMAP = {"NO_SCHEMA"}
ALLOWED_ALWAYS = {"BASE_WORKSPACE_ABSENT"}  # only when the base is mounted: the root then holds none


class Bad(Exception):
    """The knowledge base or the plan is wrong for this check: exit 3."""


def run(folder, gen):
    design, context, render_mod = gen.design, gen.context, gen.render
    report, knowledge = gen.report, gen.knowledge
    folder = Path(folder)
    rep = report.Report(str(folder))

    result = design.check(folder, generated=True)
    if result.exit_code != 0:
        design.show(result)
        rep.add("SCAFFOLD_DESIGN_INCOMPLETE", f"design.py exits {result.exit_code}")
        return report.render([rep], header="Scaffold check")
    ctx = context.build(result.design, gen.sql_rows())
    try:
        data = gen.load_manifest()
        jobs = gen.plan(ctx, data)
    except gen.Bad as error:
        rep.add("SCAFFOLD_TEMPLATE_MISSING", str(error))
        return report.render([rep], header="Scaffold check")
    targets = [job[0] for job in jobs]
    workspaces = [w["dir"] for w in ctx["workspaces"]]

    missing = [t for t in targets if not gen.exact_exists(folder, t)]
    for target in missing[:20]:
        rep.add("SCAFFOLD_STRUCTURE_INVALID", f"{report.one_line(target)} was generated by the plan and is not there")

    try:
        check_secrets(folder, targets, ctx, rep, report)
        check_structure(folder, workspaces, ctx, rep, report, knowledge, gen)
        check_routes(folder, workspaces, rep, report, gen)
        check_validators(folder, workspaces, ctx, rep, report, gen)
    except Bad as error:
        rep.add("SCAFFOLD_TEMPLATE_MISSING", str(error))
    lines = [f"FOLDER: {report.one_line(folder)}", f"FILES: {len(targets)}", f"WORKSPACES: {', '.join(workspaces)}"]
    return report.render([rep], header="Scaffold check", lines=lines)


# --- helpers ---------------------------------------------------------------------------

def read(folder, rel):
    try:
        return (Path(folder) / rel).read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return None


def code_lines(text):
    """`text` without its comment lines: a `#` comment may name ${VAR} as prose, and declares nothing."""
    return "\n".join(line for line in text.splitlines() if not line.lstrip().startswith("#"))


def walk_json(node, path=()):
    """(key path, leaf) for every scalar of a JSON document; list items add their index."""
    if isinstance(node, dict):
        for key, value in node.items():
            yield from walk_json(value, path + (key,))
    elif isinstance(node, list):
        for index, value in enumerate(node):
            yield from walk_json(value, path + (str(index),))
    else:
        yield path, node


def compose_services(text):
    """{service: {env key: value}} from the generated compose file (its own format: 2-space services, 6-space env)."""
    services, current, in_env = {}, None, False
    in_services = False
    for line in text.splitlines():
        if re.match(r"^services:\s*$", line):
            in_services, current = True, None
            continue
        if re.match(r"^[a-z]", line):
            in_services = False
        if not in_services:
            continue
        match = re.match(r"^  ([A-Za-z0-9_.\-]+):\s*$", line)
        if match:
            current, in_env = match.group(1), False
            services[current] = {}
            continue
        if current is None:
            continue
        if re.match(r"^    environment:\s*$", line):
            in_env = True
            continue
        if re.match(r"^    [a-z]", line):
            in_env = False
        if in_env:
            pair = re.match(r'^      ([A-Za-z0-9_.\-]+):\s*"?(.*?)"?\s*$', line)
            if pair:
                services[current][pair.group(1)] = pair.group(2)
    return services


# --- 1. secrets ------------------------------------------------------------------------

def check_secrets(folder, targets, ctx, rep, report):
    rep.ran("secrets")
    used = {}
    settings = [t for t in targets if re.fullmatch(r"src/[^/]+/appsettings[^/]*\.json", t)]
    for rel in settings:
        text = read(folder, rel)
        try:
            doc = json.loads(text or "")
        except ValueError as error:
            rep.add("SCAFFOLD_STRUCTURE_INVALID", f"{rel} is not JSON: {error}")
            continue
        for path, leaf in walk_json(doc):
            if not isinstance(leaf, str):
                continue
            key = ".".join(path)
            report.debug("check.secrets", "value", path=rel, key=key)
            if any(SECRET_KEY.search(part) for part in path) and not WHOLE_PLACEHOLDER.match(leaf):
                rep.add("SCAFFOLD_LITERAL_SECRET", f"{rel}: `{report.one_line(key)}` holds a literal, not one ${{VAR}}")
            for name in PLACEHOLDER.findall(leaf):
                used.setdefault(name, rel)

    compose_rel = "docker/docker-compose.yml"
    compose = read(folder, compose_rel)
    services = {}
    if compose is not None:
        services = compose_services(compose)
        for line in compose.splitlines():
            pair = YAML_PAIR.match(line)
            if not pair or not pair.group(3) or pair.group(3) in ("|", ">"):
                continue
            key, value = pair.group(2), pair.group(3).strip('"')
            report.debug("check.secrets", "value", path=compose_rel, key=key)
            if SECRET_KEY.search(key) and not WHOLE_PLACEHOLDER.match(value):
                rep.add("SCAFFOLD_LITERAL_SECRET", f"{compose_rel}: `{report.one_line(key)}` holds a literal, not one ${{VAR}}")
        for name in PLACEHOLDER.findall(code_lines(compose)):
            used.setdefault(name, compose_rel)

    for rel in targets:
        if rel.startswith(("docs/", "workspaces/")) or rel == "docker/.env.example":
            continue
        text = read(folder, rel)
        if text is None:
            continue
        if PRIVATE_KEY.search(text):
            rep.add("SCAFFOLD_LITERAL_SECRET", f"{rel} holds a private key")
        for number, line in enumerate(text.splitlines(), 1):
            found = LITERAL_SECRET.search(line)
            if found:
                rep.add("SCAFFOLD_LITERAL_SECRET", f"{rel}:{number} holds `{found.group(1)}` with a literal value")
        if rel.endswith(("Dockerfile", "dynamic.yml")) and (rel.startswith("src/") or rel.startswith("docker/")):
            for name in PLACEHOLDER.findall(code_lines(text)):
                used.setdefault(name, rel)

    env = read(folder, "docker/.env.example") or ""
    declared_env = set(re.findall(r"(?m)^([A-Z][A-Z0-9_]*)=", env))
    configuration = read(folder, "docs/configuration.md") or ""
    declared_doc = set(re.findall(r"\*\*\$\{([A-Za-z_][A-Za-z0-9_]*)\}\*\*", configuration))
    for name, where in sorted(used.items()):
        if name in SHELL_ONLY:
            continue
        if name not in declared_env:
            rep.add("SCAFFOLD_VAR_UNDECLARED", f"${{{name}}} is used in {where} and not declared in docker/.env.example")
        if name not in declared_doc:
            rep.add("SCAFFOLD_VAR_UNDECLARED", f"${{{name}}} is used in {where} and not declared in docs/configuration.md")

    # every placeholder of an appsettings file is set, under the same key, by the service that runs it
    for dep in ctx["deployments"]:
        env_of = services.get(dep["id"])
        if env_of is None:
            continue
        for rel in (f"{dep['api_dir']}/appsettings.json", f"{dep['api_dir']}/{dep['settings_file']}"):
            try:
                doc = json.loads(read(folder, rel) or "")
            except ValueError:
                continue
            for path, leaf in walk_json(doc):
                if isinstance(leaf, str) and "${" in leaf:
                    key = "__".join(path)
                    if key not in env_of:
                        rep.add("SCAFFOLD_VAR_UNDECLARED",
                                f"{rel}: `{'.'.join(path)}` is a placeholder the compose service `{dep['id']}` does not set "
                                f"as {key}")
                    elif env_of[key].replace("https://", "") != leaf.replace("https://", ""):
                        rep.add("SCAFFOLD_VAR_UNDECLARED",
                                f"{rel}: `{'.'.join(path)}` is {leaf} but compose sets {env_of[key]}")


# --- 2. structure ----------------------------------------------------------------------

def shape(path, row, rep, report, rel):
    """Parse an XML file and hold it to its workspace-minimum row; the root element is returned."""
    try:
        root = ET.parse(path).getroot()
    except (ET.ParseError, OSError) as error:
        rep.add("SCAFFOLD_STRUCTURE_INVALID", f"{rel} is not well-formed XML: {report.one_line(error)}")
        return None
    report.debug("check.structure", "file", path=rel, root=root.tag)
    if root.tag != row["Root"]:
        rep.add("SCAFFOLD_STRUCTURE_INVALID", f"{rel} has the root `{root.tag}`; expected `{row['Root']}`")
        return None
    from_table = row["Required"].split()
    for token in from_table:
        if token.startswith("@"):
            if token[1:] not in root.attrib:
                rep.add("SCAFFOLD_STRUCTURE_INVALID", f"{rel}: the root `{root.tag}` lacks the attribute `{token[1:]}`")
        elif root.find(token) is None:
            rep.add("SCAFFOLD_STRUCTURE_INVALID", f"{rel}: the root `{root.tag}` lacks the element `{token}`")
    return root


def check_structure(folder, workspaces, ctx, rep, report, knowledge, gen):
    rep.ran("structure")
    rows = knowledge.index("workspace-minimum")
    for row in rows.values():
        for rule in row["Rule"].split():
            if rule not in KNOWN_RULES:
                raise Bad(f"the workspace-minimum table names the rule `{rule}`, which this check does not know")
    map_row = rows["_application.sitemap"]
    tree_row = rows["FM/_PROFILE/<profile>/<group>/_tree.xml"]
    node_row = rows["FM/_PROFILE/<profile>/<group>/<node>.xml"]
    for directory in workspaces:
        base = Path(folder) / "workspaces" / directory
        maps = ["_application.sitemap"] + [f"_application-{i['name']}.sitemap" for w in ctx["workspaces"]
                                            if w["dir"] == directory and w["shared"] for i in w["instances"]]
        profiles = sorted(p.name for p in os.scandir(base / "FM" / "_PROFILE") if p.is_dir()) \
            if gen.exact_exists(folder, f"workspaces/{directory}/FM/_PROFILE") else []
        for name in maps:
            rel = f"workspaces/{directory}/{name}"
            if not gen.exact_exists(folder, rel):
                rep.add("SCAFFOLD_STRUCTURE_INVALID", f"{rel} is missing")
                continue
            root = shape(base / name, map_row, rep, report, rel)
            if root is None:
                continue
            tabs = [n for n in root.iter("mapNode") if n.get("type") == "PROFILE"]
            for profile in profiles:
                if not any(n.get("content") == profile for n in tabs):
                    rep.add("SCAFFOLD_STRUCTURE_INVALID", f"{rel} has no PROFILE tab for the profile `{profile}`")
        for profile in profiles:
            groups = sorted(g.name for g in os.scandir(base / "FM" / "_PROFILE" / profile) if g.is_dir())
            if "Members" not in groups:
                rep.add("SCAFFOLD_STRUCTURE_INVALID", f"workspaces/{directory}/FM/_PROFILE/{profile} has no Members group")
            for group in groups:
                folder_rel = f"workspaces/{directory}/FM/_PROFILE/{profile}/{group}"
                tree_path = base / "FM" / "_PROFILE" / profile / group / "_tree.xml"
                if not gen.exact_exists(folder, f"{folder_rel}/_tree.xml"):
                    rep.add("SCAFFOLD_STRUCTURE_INVALID", f"{folder_rel}/_tree.xml is missing")
                    continue
                root = shape(tree_path, tree_row, rep, report, f"{folder_rel}/_tree.xml")
                if root is None:
                    continue
                for node in root.iter("Folder"):
                    if not node.get("control"):
                        continue
                    node_rel = f"{folder_rel}/{node.get('name')}.xml"
                    if not gen.exact_exists(folder, node_rel):
                        rep.add("SCAFFOLD_STRUCTURE_INVALID", f"{node_rel} is missing — the tree folder `{node.get('name')}` opens it")
                    else:
                        shape(tree_path.parent / f"{node.get('name')}.xml", node_row, rep, report, node_rel)


# --- 3. routes -------------------------------------------------------------------------

def routes_of(node):
    """Every dict with a `path` and `content` under a sitemap's routes, nested routers' routes included."""
    if isinstance(node, dict):
        if "path" in node and "content" in node:
            yield node
        for value in node.values():
            yield from routes_of(value)
    elif isinstance(node, list):
        for value in node:
            yield from routes_of(value)


def components_of(node):
    if isinstance(node, dict):
        if "type" in node:
            yield node
        for value in node.values():
            yield from components_of(value)
    elif isinstance(node, list):
        for value in node:
            yield from components_of(value)


def check_routes(folder, workspaces, rep, report, gen):
    rep.ran("routes")
    for directory in workspaces:
        prefix = f"workspaces/{directory}"
        sitemap_rel = f"{prefix}/FM/_COMPONENTS/sitemap.json"
        if not gen.exact_exists(folder, sitemap_rel):
            rep.add("SCAFFOLD_ROUTE_UNRESOLVED", f"{sitemap_rel} is missing")
            continue
        try:
            sitemap = json.loads(read(folder, sitemap_rel) or "")
        except ValueError as error:
            rep.add("SCAFFOLD_ROUTE_UNRESOLVED", f"{sitemap_rel} is not JSON: {report.one_line(error)}")
            continue
        table = sitemap.get("routes") if isinstance(sitemap, dict) else None
        listed = table.get("routes") if isinstance(table, dict) else None
        if not isinstance(listed, list) or not listed or not isinstance(listed[0], dict):
            rep.add("SCAFFOLD_ROUTE_UNRESOLVED", f"{sitemap_rel} has no routes list")
            continue
        landing = listed[0].get("path")
        if not isinstance(landing, str) or landing in ("", "/"):
            rep.add("SCAFFOLD_ROUTE_UNRESOLVED", f"{sitemap_rel}: the landing route, the first, is `{report.one_line(landing)}`; "
                    "the shell drops a route whose path is `/`")
        login_seen = False
        for route in routes_of(table):
            path = route.get("path")
            for component in components_of(route.get("content")):
                kind, name = component.get("type"), component.get("name")
                if kind == "page" and isinstance(name, str):
                    page_rel = f"{prefix}/FM/_COMPONENTS/Page/{name}.json"
                    report.debug("check.routes", "route", path=path, page=page_rel)
                    if not gen.exact_exists(folder, page_rel):
                        rep.add("SCAFFOLD_ROUTE_UNRESOLVED", f"{sitemap_rel}: route `{report.one_line(path)}` names the page "
                                f"`{report.one_line(name)}`, and {page_rel} does not exist")
                    elif path == "/login":
                        login_seen = True
                        try:
                            page = json.loads(read(folder, page_rel) or "")
                        except ValueError:
                            page = None
                        logins = [c for c in components_of(page) if c.get("type") == "login"]
                        if not any(isinstance(c.get("authenticationMethods"), list) and c["authenticationMethods"]
                                   for c in logins):
                            rep.add("SCAFFOLD_ROUTE_UNRESOLVED", f"{page_rel} holds no login component with authentication methods")
                elif kind == "router" and isinstance(name, str):
                    if not gen.exact_exists(folder, f"{prefix}/FM/_PROFILE/{name}"):
                        rep.add("SCAFFOLD_ROUTE_UNRESOLVED", f"{sitemap_rel}: route `{report.one_line(path)}` opens the router "
                                f"`{report.one_line(name)}`, which has no profile folder")
        if not login_seen:
            rep.add("SCAFFOLD_ROUTE_UNRESOLVED", f"{sitemap_rel} has no `/login` route with a page")


# --- 4. validators ---------------------------------------------------------------------

def collect(base, names):
    found = []
    for directory, subdirs, files in os.walk(base):
        subdirs[:] = sorted(subdirs)
        for name in sorted(files):
            if name in names:
                found.append(str(Path(directory) / name))
    return found


def run_validator(folder, script, args, rep, report, sitemap_ok=True):
    command = [sys.executable, str(SCRIPTS / script), *args]
    done = subprocess.run(command, capture_output=True, text=True, cwd=str(folder))
    text = done.stdout + "\n" + done.stderr
    rejected = []
    lines = text.splitlines()
    for index, line in enumerate(lines):
        found = FINDING.match(line)
        if not found:
            continue
        label, code, rest = found.groups()
        if label == "INFO":
            continue
        if code == "DEPENDENCY_MISSING":
            # the message runs on: the install command is on the lines after it
            more = " ".join(l.strip() for l in lines[index + 1:index + 4] if l.strip())
            rep.add("DEPENDENCY_MISSING", f"{rest} {more}".strip())
            return
        if code in ALLOWED_ON_SITEMAP and "sitemap.json" in rest.split(" ", 1)[0]:
            continue
        if code in ALLOWED_ALWAYS:
            continue
        rejected.append(line)
    report.debug("check.validator", "ran", script=script, exit=done.returncode, rejected=len(rejected))
    for line in rejected:
        rep.add("SCAFFOLD_VALIDATION_FAILED", f"{script}: {line}")
    if done.returncode == report.EXIT_USAGE and not rejected:
        first = next((l for l in text.splitlines() if l.strip()), "exit 3 without a message")
        rep.add("SCAFFOLD_VALIDATION_FAILED", f"{script} exited 3: {first}")


def check_validators(folder, workspaces, ctx, rep, report, gen):
    rep.ran("validators")
    root = Path(folder) / "workspaces"
    for directory in workspaces:
        base = root / directory
        rel_base = f"workspaces/{directory}"
        run_validator(folder, "validate_config.py", [rel_base], rep, report)
        run_validator(folder, "resolve_components.py", [rel_base], rep, report)
        model = [os.path.relpath(p, folder) for p in collect(base / "FM" / "_DATA", {"settings.xml", "_form.xml"})]
        if model:
            run_validator(folder, "validate_model.py", [*model, "--workspaces-root", "workspaces"], rep, report)
        if ctx["has_process"]:
            process = [os.path.relpath(p, folder) for p in
                       collect(base / "FM" / "_PROCESS", {"process.xml"}) + collect(base / "FM" / "_WORKFLOW", {"_workflow.xml"})]
            if process:
                run_validator(folder, "validate_process.py", [*process, "--workspaces-root", "workspaces"], rep, report)
